CREATE TABLE NOTIFICATION_USER_GROUPS(
    USER_GROUP_ID       INT             PRIMARY KEY     auto_increment,
    USER_GROUP          VARCHAR(50)     UNIQUE,
    USER_GROUP_QUERY    VARCHAR(1000)   NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL        DEFAULT 'Active',
    CREATED_BY          VARCHAR(50),
    CREATED_TIME        TIMESTAMP                       DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY     VARCHAR(20),
    LAST_UPDATED_TIME   TIMESTAMP                       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)